[region]
RESEARCH_REGIONS = ['MELBOURNE CITY']

[period]
TZ = 'Australia/Sydney'
TRAINING_START_TIME = '2021-11-03 11:00:00'
TRAINING_END_TIME = '2021-11-17 11:00:00'
TESTING_START_TIME = '2021-11-17 11:00:00'
TESTING_END_TIME = '2021-11-19 11:00:00'

[window]
FORWARD_STEPS = 36
BACKWARD_STEPS = 12
WINDOW_MIN = 5

